import Head from "next/head";

function Home() {
  return (
    <div className="flex flex-col">
      <Head>
        <title>AnimeDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
    </div>
  );
}

export default Home;

// internal components

function AnimeCard({ anime }) {
  return (
    <div className="flex h-64 gap-3 rounded-md shadow-lg">
      <div
        className="relative flex aspect-[3/4] h-full flex-row bg-cover"
        style={{
          backgroundImage: `url(${anime.attributes.posterImage.small})`,
        }}
      >
        <div className="absolute inset-x-0 bottom-0 flex bg-black/50 p-2 backdrop-blur-md">
          <div className="text-white">
            <h2 className="text-md">{anime.attributes.canonicalTitle}</h2>
            <h3></h3>
          </div>
        </div>
      </div>
      <div className="flex flex-col gap-2">
        <div className="flex justify-between p-2">
          <div className="text-sm">
            {anime.attributes.episodeCount} episodes
          </div>
        </div>
        <div className="overflow-auto text-sm">{anime.attributes.synopsis}</div>
      </div>
    </div>
  );
}
